### ISSUE TITLE
problem with compilation

### ISSUE THREAD

**Issue by cryptomaxsun** [SuB1X-Coin/zSub1x#4]
This issue tracker is only for technical issues related to zSub1x Core.
General zSub1x questions and/or support requests and are best directed to the [zSub1x Slack](http://zsub1x.slack.com).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of zSub1x Core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log`, `db.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

VPS Ubunttu 16.04
CPU Xeon 1 thread 3.3 Ghz
1 Gb
19 Gb
SSD
> qt/multisigdialog.cpp:27:33: fatal error: QtWidgets/QHBoxLayout: No such file or directory
> compilation terminated.
> Makefile:5762: recipe for target 'qt/qt_libbitcoinqt_a-multisigdialog.o' failed
> make[2]: *** [qt/qt_libbitcoinqt_a-multisigdialog.o] Error 1
> make[2]: Leaving directory '/home/max/zSub1x/src'
> Makefile:7823: recipe for target 'all-recursive' failed
> make[1]: *** [all-recursive] Error 1
> make[1]: Leaving directory '/home/max/zSub1x/src'
> Makefile:611: recipe for target 'all-recursive' failed

**Comment by Remapper** [comment]
Closing as no more reports
