### ISSUE TITLE
http://sub1x.mn.zone/ is down

### ISSUE THREAD

**Issue by jakeonfire** [SuB1X-Coin/zSub1x#5]
This issue tracker is only for technical issues related to zSub1x Core.
General zSub1x questions and/or support requests and are best directed to the [zSub1x Slack](http://zsub1x.slack.com).

<img width="659" alt="Screen Shot 2019-08-30 at 9 15 24 PM" src="https://user-images.githubusercontent.com/68826/64059155-546ed680-cb6b-11e9-86e9-7d5cc38c73e3.png">

### Describe the issue
http://sub1x.mn.zone/ is down. i relied on it to know the status of my MN and to see, for example, if there was a new version of the wallet.

### Can you reliably reproduce the issue?
yes

#### If so, please list the steps to reproduce below:
1. navigate to http://sub1x.mn.zone/ in a browser

### Expected behavior
the list of masternodes appears

### Actual behavior
DNS error

**Comment by thewatchers1456** [comment]
MN.Zone delisted SUB1X for not paying the 0.5 BTC fee. 

https://sub1x.ccore.online/ is the alternative.
